all:	pdf

tex:
	@latex main.tex

fast:
	@pdflatex main.tex

pdf:
	@pdflatex main.tex
	@pdflatex main.tex

clean:
	@echo "Cleaning files..."
	@rm -f *.aux
	@rm -f *.bbl
	@rm -f *.blg
	@rm -f *.dvi
	@rm -f *.log
	@rm -f *.out
	@rm -f *.ps
	@rm -f *.toc
	@rm -f *.synctex.gz
	@rm -f *.backup
	@rm -f *~

